# -*- coding: utf-8 -*-
"""Architecture fitness function — generates the module dependency graph + metrics
from the code and checks the dependency direction (rules 6/7/8).

  * Rule 6: enforces the allowed import direction (API→Services→Domain→
    Repositories→Infrastructure; core/models/schemas/utils are foundation).
    UPWARD or CIRCULAR intra-app imports are VIOLATIONS. Same-layer (peer) edges
    are reported as tracked debt.
  * Rule 7: emits a Mermaid diagram of app/ package dependencies.
  * Rule 8: emits per-package metrics (files, LOC, largest file) — architecture
    signal, not just a line count.

Run:  python tools/arch_graph.py            # writes docs/ARCHITECTURE.md
      python tools/arch_graph.py --check    # exit 1 if any hard violation (CI)
"""
from __future__ import annotations
import ast
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
APP = os.path.join(ROOT, "app")

# Layer rank — higher may import lower, never the reverse. Peers (equal) are debt.
# NOTE: optimization/economics are physically under services/ during Phase 3 but
# are DOMAIN-tier by intent (promoted to domain/ in P6); ranked here as domain.
# Higher may import lower. models/schemas are the innermost entities (rank 0);
# everything may depend on them downward. api is outermost.
LAYER_RANK = {
    "api": 5, "services": 4, "domain": 3, "repositories": 2,
    "core": 1, "utils": 1, "infrastructure": 1,
    "models": 0, "schemas": 0,
}
# modules physically in services/ that are domain-tier by intent (tracked debt D1/D2)
DOMAIN_BY_INTENT = {"services.optimization_service", "services.economics"}


def _pkg(rel):  # app/services/x.py -> "services.x" ; app/core/config.py -> "core.config"
    return rel[:-3].replace(os.sep, ".").removesuffix(".__init__")


def _layer(mod):
    return mod.split(".")[0]


def _rank(mod):
    if mod in DOMAIN_BY_INTENT:
        return LAYER_RANK["domain"]
    return LAYER_RANK.get(_layer(mod), 99)


def scan():
    mods, edges, metrics = {}, set(), {}
    for dirpath, _, files in os.walk(APP):
        for fn in files:
            if not fn.endswith(".py"):
                continue
            path = os.path.join(dirpath, fn)
            rel = os.path.relpath(path, APP)
            mod = _pkg(rel)
            src = open(path, encoding="utf-8").read()
            loc = len(src.splitlines())
            layer = _layer(mod)
            m = metrics.setdefault(layer, {"files": 0, "loc": 0, "largest": ("", 0)})
            m["files"] += 1
            m["loc"] += loc
            if loc > m["largest"][1]:
                m["largest"] = (mod, loc)
            mods[mod] = loc
            for node in ast.walk(ast.parse(src)):
                tgt = None
                if isinstance(node, ast.ImportFrom) and node.module and node.module.startswith("app."):
                    tgt = node.module[len("app."):]
                elif isinstance(node, ast.Import):
                    for a in node.names:
                        if a.name.startswith("app."):
                            tgt = a.name[len("app."):]
                if tgt and _layer(tgt) != _layer(mod) or (tgt and tgt in DOMAIN_BY_INTENT):
                    edges.add((_layer(mod) if mod not in DOMAIN_BY_INTENT else "domain",
                               "domain" if tgt in DOMAIN_BY_INTENT else _layer(tgt), mod, tgt))
    return mods, edges, metrics


def analyse():
    mods, edges, metrics = scan()
    violations, peers = [], []
    for a_layer, b_layer, a_mod, b_mod in edges:
        ra, rb = _rank(a_mod), _rank(b_mod)
        if ra < rb:
            violations.append(f"UPWARD: {a_mod} (rank {ra}) -> {b_mod} (rank {rb})")
        elif ra == rb and a_layer != b_layer:
            peers.append(f"peer: {a_mod} -> {b_mod}")
    return mods, edges, metrics, violations, peers


def render_md(mods, edges, metrics, violations, peers):
    layer_edges = sorted({(a, b) for a, b, _, _ in edges if a != b})
    lines = ["# PREDAIOT — Architecture (auto-generated by tools/arch_graph.py)", "",
             "> Do not edit by hand. Regenerate with `python tools/arch_graph.py`.", "",
             "## Package dependency graph", "", "```mermaid", "graph TD"]
    for a, b in layer_edges:
        lines.append(f"    {a} --> {b}")
    lines += ["```", "", "## Package metrics", "",
              "| Layer | Files | LOC | Largest module |", "|---|--:|--:|---|"]
    for layer in sorted(metrics, key=lambda k: -LAYER_RANK.get(k, 99)):
        m = metrics[layer]
        lines.append(f"| {layer} | {m['files']} | {m['loc']} | {m['largest'][0]} ({m['largest'][1]} L) |")
    lines += ["", "## Dependency-rule check", "",
              f"- Hard violations (upward/circular): **{len(violations)}**"]
    for v in violations:
        lines.append(f"  - ❌ {v}")
    lines.append(f"- Peer edges (same-layer, tracked as debt D1/D11): **{len(peers)}**")
    for p in peers:
        lines.append(f"  - 🟡 {p}")
    lines += ["", f"- Modules scanned: {len(mods)}", ""]
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    mods, edges, metrics, violations, peers = analyse()
    md = render_md(mods, edges, metrics, violations, peers)
    if "--check" in sys.argv:
        print(f"violations={len(violations)} peers={len(peers)}")
        for v in violations:
            print("  ", v)
        sys.exit(1 if violations else 0)
    out = os.path.join(ROOT, "docs", "ARCHITECTURE.md")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    open(out, "w", encoding="utf-8").write(md)
    print(f"wrote {out}  ({len(mods)} modules, {len(violations)} violations, {len(peers)} peer edges)")
